(function(g){var window=this;'use strict';var W5a=function(a){g.W.call(this,{F:"div",N:"ytp-inline-preview-ui"});this.Ze=!1;this.player=a;this.T(a,"onStateChange",this.cL);this.T(a,"videodatachange",this.Gn);this.T(a,"onInlinePreviewModeChange",this.l_);this.Ee=new g.Vn(this.jt,null,this);g.M(this,this.Ee)},I6=function(a){g.eO.call(this,a);
this.j=new W5a(this.player);g.M(this,this.j);this.j.hide();g.BN(this.player,this.j.element,4);a.isInline()&&(this.load(),g.jo(a.getRootNode(),"ytp-inline-preview-mode",!0),this.player.V().K("web_rounded_containers")&&g.jo(a.getRootNode(),"ytp-rounded-inline-preview",!0),this.player.V().K("web_inline_player_disable_scrubbing")&&g.jo(a.getRootNode(),"ytp-inline-preview-mode-no-scrubbing",!0))};
g.v(W5a,g.W);g.k=W5a.prototype;
g.k.wI=function(){this.tooltip=new g.aS(this.player,this);g.M(this,this.tooltip);g.BN(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Ic=new g.ZO(this.player);g.M(this,this.Ic);var a=["ytp-inline-preview-scrim"];this.player.V().K("web_inline_player_expand_to_watch")||a.push("ytp-inline-preview-scrim-clear");this.gi=new g.W({F:"div",Fa:a});g.M(this,this.gi);this.gi.Ca(this.element);this.T(this.gi.element,"click",this.HD);this.player.V().K("web_inline_player_expand_to_watch")&&(a=new g.M2(this.player,
this),g.M(this,a),a.Ca(this.gi.element));this.ri=new g.MR(this.player,this);g.M(this,this.ri);this.ri.Ca(this.gi.element);this.controls=new g.W({F:"div",N:"ytp-inline-preview-controls"});g.M(this,this.controls);this.controls.Ca(this.element);a=new g.vQ(this.player,this);g.M(this,a);a.Ca(this.controls.element);a=new g.KR(this.player,this);g.M(this,a);a.Ca(this.controls.element);this.Cc=new g.KQ(this.player,this);g.M(this,this.Cc);g.BN(this.player,this.Cc.element,4);this.T(this.player,"appresize",this.Cb);
this.T(this.player,"fullscreentoggled",this.Cb);this.Cb()};
g.k.show=function(){g.Wn(this.Ee);this.Ze||(this.wI(),this.Ze=!0);0!==this.player.getPlayerState()&&g.W.prototype.show.call(this);this.Cc.show()};
g.k.hide=function(){this.Ee.stop();g.W.prototype.hide.call(this);this.player.isInline()||this.Ze&&this.Cc.hide()};
g.k.ra=function(){g.W.prototype.ra.call(this)};
g.k.HD=function(a){a.target!==this.gi.element||this.player.V().K("web_inline_player_expand_to_watch")||this.player.Pa("onExpandInlinePreview",a)};
g.k.l_=function(){g.jo(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.Yd=function(){this.Cc.hc();this.ri.hc()};
g.k.jt=function(){this.Yd();g.Wn(this.Ee)};
g.k.Cb=function(){g.aR(this.Cc,0,this.player.gb().getPlayerSize().width,!1);g.NQ(this.Cc)};
g.k.cL=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.Gn=function(a,b){this.player.isInline()&&g.jo(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.iF)};
g.k.wc=function(){return this.tooltip};
g.k.Wf=function(){return!1};
g.k.Hg=function(){return!1};
g.k.Do=function(){return!1};
g.k.hk=function(){return!1};
g.k.xA=function(){};
g.k.Ip=function(){};
g.k.Iv=function(){};
g.k.Lm=function(){return null};
g.k.Yy=function(){return null};
g.k.fk=function(){return new g.wl(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.At=function(a,b,c,d,e){var f=d=0,h=0,l=g.Kl(a);if(b){c=g.eo(b,"ytp-miniplayer-expand-watch-page-button");var m=g.eo(b,"ytp-mute-button"),n=g.eo(b,"ytp-subtitles-button"),p=g.Il(b,this.element);b=g.Kl(b);d=p.y+40;c&&(h=8);if(n||m)h=p.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.gb().getPlayerSize().width;h=g.Eg(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.Dn=function(){};
g.k.dl=function(){return!1};
g.k.yA=function(){};
g.k.HB=function(){};g.v(I6,g.eO);I6.prototype.Dj=function(){return!1};
I6.prototype.load=function(){this.player.hideControls();this.j.show()};
I6.prototype.unload=function(){this.player.showControls();this.j.hide()};g.dO("inline_preview",I6);})(_yt_player);
